"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Score__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Score__factory_1 = require("./Score__factory");
Object.defineProperty(exports, "Score__factory", { enumerable: true, get: function () { return Score__factory_1.Score__factory; } });
