/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Score {
  export type TournamentScoreStruct = {
    tournamentID: BigNumberish;
    player1: AddressLike;
    player2: AddressLike;
    scorePlayer1: BigNumberish;
    scorePlayer2: BigNumberish;
    timestamp: BigNumberish;
  };

  export type TournamentScoreStructOutput = [
    tournamentID: bigint,
    player1: string,
    player2: string,
    scorePlayer1: bigint,
    scorePlayer2: bigint,
    timestamp: bigint
  ] & {
    tournamentID: bigint;
    player1: string;
    player2: string;
    scorePlayer1: bigint;
    scorePlayer2: bigint;
    timestamp: bigint;
  };
}

export interface ScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addScore"
      | "getAllScores"
      | "getScore"
      | "getScoreCount"
      | "getScoresForTournament"
      | "owner"
      | "renounceOwnership"
      | "scores"
      | "scoresByTournament"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "ScoreAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addScore",
    values: [Score.TournamentScoreStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllScores",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScoresForTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scoresByTournament",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getScoreCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScoresForTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scores", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scoresByTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreAddedEvent {
  export type InputTuple = [
    tournamentID: BigNumberish,
    player1: AddressLike,
    player2: AddressLike,
    scorePlayer1: BigNumberish,
    scorePlayer2: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tournamentID: bigint,
    player1: string,
    player2: string,
    scorePlayer1: bigint,
    scorePlayer2: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tournamentID: bigint;
    player1: string;
    player2: string;
    scorePlayer1: bigint;
    scorePlayer2: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Score extends BaseContract {
  connect(runner?: ContractRunner | null): Score;
  waitForDeployment(): Promise<this>;

  interface: ScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addScore: TypedContractMethod<
    [s: Score.TournamentScoreStruct],
    [void],
    "nonpayable"
  >;

  getAllScores: TypedContractMethod<
    [],
    [Score.TournamentScoreStructOutput[]],
    "view"
  >;

  getScore: TypedContractMethod<
    [index: BigNumberish],
    [Score.TournamentScoreStructOutput],
    "view"
  >;

  getScoreCount: TypedContractMethod<[], [bigint], "view">;

  getScoresForTournament: TypedContractMethod<
    [tournamentID: BigNumberish],
    [Score.TournamentScoreStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scores: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        tournamentID: bigint;
        player1: string;
        player2: string;
        scorePlayer1: bigint;
        scorePlayer2: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  scoresByTournament: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        tournamentID: bigint;
        player1: string;
        player2: string;
        scorePlayer1: bigint;
        scorePlayer2: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addScore"
  ): TypedContractMethod<
    [s: Score.TournamentScoreStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllScores"
  ): TypedContractMethod<[], [Score.TournamentScoreStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<
    [index: BigNumberish],
    [Score.TournamentScoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScoreCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScoresForTournament"
  ): TypedContractMethod<
    [tournamentID: BigNumberish],
    [Score.TournamentScoreStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scores"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        tournamentID: bigint;
        player1: string;
        player2: string;
        scorePlayer1: bigint;
        scorePlayer2: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "scoresByTournament"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        tournamentID: bigint;
        player1: string;
        player2: string;
        scorePlayer1: bigint;
        scorePlayer2: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreAdded"
  ): TypedContractEvent<
    ScoreAddedEvent.InputTuple,
    ScoreAddedEvent.OutputTuple,
    ScoreAddedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScoreAdded(uint256,address,address,uint8,uint8,uint256)": TypedContractEvent<
      ScoreAddedEvent.InputTuple,
      ScoreAddedEvent.OutputTuple,
      ScoreAddedEvent.OutputObject
    >;
    ScoreAdded: TypedContractEvent<
      ScoreAddedEvent.InputTuple,
      ScoreAddedEvent.OutputTuple,
      ScoreAddedEvent.OutputObject
    >;
  };
}
